export const RESPONSE_CODE = {
  OK: 'CS-OK',
  CREATED: 'CS-CREATED',
  NOT_FOUND: 'CE-NOT_FOUND',
  INTERNAL_SERVER_ERROR: 'CE-INTERNAL_ERROR',
} as const;
export type RESPONSE_CODE = typeof RESPONSE_CODE[keyof typeof RESPONSE_CODE];
